name: Run Go Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Adjust this to the version you are using

      - name: Install dependencies
        run: go mod tidy

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Reference the secret
        run: go run main.go
